[package]
name = "oneone-plz"
version = "0.0.5"
authors = ["darkseid", "sytten <emile@caido.io>"]
description = "HTTP/1 parser for the ParsePlz ecosystem"
repository = "https://github.com/parseplz/oneone-plz"
license = "MIT"
edition = "2024"

[dependencies]
# primitives
body-plz = "0.0.41"
buffer-plz = "0.0.3"
decompression-plz = "0.0.18"
header-plz = "0.0.37"
http-plz = { git = "https://github.com/parseplz/http-plz" }

# basic 
bytes = "1.10.1"
thiserror = "2.0.12"

[dev-dependencies]
brotli = "8.0.0"
flate2 = "1.1.0"
zstd = "0.13.3"
